# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Escaping Sloth 
tagline:          ...very slowly! 
url:              http://getpoole.com
paginate:         1
baseurl:          http://rkwrd.github.io/
author:
  name:           Arne 
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole


# page header
pages_list:
  About: "/about"
  Archive: "/archive"
  Feed: "/atom.xml"
